### ISSUE TITLE
params.grad=None ?

### ISSUE THREAD

**Issue by rl15442** [mailong25/meta-bert#1]
<img width="652" alt="Screenshot 2020-06-22 at 00 55 55" src="https://user-images.githubusercontent.com/42834831/85238107-8d8e7500-b423-11ea-8010-4de816de0810.png">

你好，我用 maml.py的时候有的params的grad会出现None, 请问这种情况怎么处理呢？

**Comment by ztl-35** [comment]
你好，我也碰到了这个问题，请问你是怎么解决的？谢谢！
